FROM python:3.12-slim

WORKDIR /app
COPY app/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY app /app

# worker metrics port
EXPOSE 9102
CMD ["python", "-m", "worker.worker"]
